SET(LIBGP_SRC
  src/core/cov.cc
  src/core/cov_factory.cc
  src/core/cov_linear_ard.cc
  src/core/cov_linear_one.cc
  src/core/cov_noise.cc
  src/core/cov_se_iso.cc
  src/core/cov_se_ard.cc
  src/core/cov_matern3_iso.cc
  src/core/cov_matern5_iso.cc
  src/core/cov_periodic.cc
  src/core/cov_periodic_matern3_iso.cc
  src/core/cov_rq_iso.cc
  src/core/cov_sum.cc
  src/core/cov_prod.cc
  src/core/input_dim_filter.cc
  src/core/gp.cc
  src/core/gp_utils.cc
  src/core/sampleset.cc
  src/core/rprop.cc
  src/core/cg.cc
)

SET(LIBGP_INTERFACES
  include/core/cov.h
  include/core/cov_factory.h
  include/core/cov_linear_ard.h
  include/core/cov_linear_one.h
  include/core/cov_noise.h
  include/core/cov_se_iso.h
  include/core/cov_se_ard.h
  include/core/cov_matern3_iso.h
  include/core/cov_matern5_iso.h
  include/core/cov_periodic.h
  include/core/cov_periodic_matern3_iso.h
  include/core/cov_rq_iso.h
  include/core/cov_sum.h
  include/core/cov_prod.h
  include/core/input_dim_filter.h
  include/core/gp.h
  include/core/gp_utils.h
  include/core/sampleset.h
  include/core/rprop.h
  include/core/cg.h
)


SET(LIBGP_WRAPPER_SRC
  src/wrapper/gp_wrap.cpp
)

SET(LIBGP_WRAPPER_INTERFACES
  include/wrapper/gp_wrap.h
)
